services:
  notebooks:
    build: 
      context: .
    container_name: qosf_notebook
    network_mode: host
    user: root
    group_add:
      - users
    ports:
      - 8888:8888
    working_dir: /home/qosf/work/notebooks
    volumes:
      - ./:/home/qosf/work
    environment:
      - JUPYTER_TOKEN=1234
      - NB_USER=qosf
      - NB_UID=${HOST_UID}
      - NB_GID=${HOST_GID}
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
